BEGIN TRANSACTION;

/*CREATE TABLE CALLED EMPLOYEE*/
CREATE TABLE EMPLOYEE(
Id int PRIMARY KEY,
Name varchar(255),
Salary int NOT NULL
);

INSERT INTO EMPLOYEE VALUES('1','ABC','120000');
INSERT INTO EMPLOYEE VALUES('2','XYZ','20500');
INSERT INTO EMPLOYEE VALUES('3','WASD','2900');
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE ORDER BY Name ;

SELECT Name FROM EMPLOYEE ORDER BY Name DESC;