BEGIN TRANSACTION;

/*CREATE TABLE CALLED EMPLOYEE*/
CREATE TABLE EMPLOYEE(
Id int PRIMARY KEY,
Name varchar(255),
Salary int NOT NULL
);

INSERT INTO EMPLOYEE VALUES('1','ABC','120000');
INSERT INTO EMPLOYEE VALUES('2','XYZ','20500');
INSERT INTO EMPLOYEE VALUES('3','WASD','2900');
INSERT INTO EMPLOYEE VALUES('4','HJKL','87832');
SELECT * FROM EMPLOYEE;

SELECT COUNT(Id), Salary FROM EMPLOYEE
GROUP BY Salary HAVING COUNT(Id) >=2;